---
apiVersion: v1
kind: Namespace
metadata:
  name: beyond-kvc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: beyond-kvc-daemon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: beyond-kvc-daemon
subjects:
- kind: ServiceAccount
  name: beyond-kvc-daemon
  namespace: beyond-kvc
