---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: beyond-kvc
  namespace: beyond-kvc
  labels:
    myapp: beyond-kvc
spec:
  selector:
    matchLabels:
      name: beyond-kvc
  template:
    metadata:
      labels:
        name: beyond-kvc
    spec:
      hostPID: true
      # hostNetwork: true
      serviceAccountName: beyond-kvc-daemon
      serviceAccount: beyond-kvc-daemon
      # tolerations:
      # - key: node-role.kubernetes.io/master
      #   effect: NoSchedule
      nodeSelector:
        # Match only specific nodes requesting it:
        #   oc label node worker-0 unsupported.example.com/beyond-kvc=""
        unsupported.example.com/beyond-kvc: ""
      containers:
      - name: beyond-kvc
        # image: quay.io/wcaban/beyond-kvc:latest
        image: registry.access.redhat.com/ubi8/ubi:latest
        # resources:
        #   limits:
        #     memory: 200Mi
        #     cpu: 1000m
        #   requests:
        #     cpu: 100m
        #     memory: 200Mi
        securityContext:
          privileged: true
        command:
          - /bin/bash
          - -c
          - sleep infinity
          # For automatic kmod loading
          #- /usr/local/bin/entrypoint.sh
        env:
          # space sperated list of kmods to load
          - name: KMOD_NAMES
            value: "rte_kni.ko"
      terminationGracePeriodSeconds: 30
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: FallbackToLogsOnError
    # updateStrategy:
    #   rollingUpdate:
    #     maxUnavailable: 1
    #   type: RollingUpdate